### ISSUE TITLE
Kept running into issues, here's my two cents for anyone else.

### ISSUE THREAD

**Issue by nahventure** [dcerisano/cloudflare-dynamic-dns#1]
don't know why.
don't know how.
skydived into the api docs and tried my best. 

Here's what I replaced the script for getting the a-record ID with.

https://pastebin.com/pVzuQjF4  the other one kept giving errors, syntax errors mostly.

({"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}curl: (6) Could not resolve host: application)

Using Debian 10 with latest curl.

**Comment by hcuk94** [comment]
Thank you! I was having similar issues and this was the quickest resolution for me.

**Comment by dcerisano** [comment]
Looks like you did not have your `dynamic` A-Record created in CF. 
Also please post suggested code changes as a PR.
No one else is reporting this issue.
