### ISSUE TITLE
question about CNAME

### ISSUE THREAD

**Issue by dogrocker** [dcerisano/cloudflare-dynamic-dns#2]
`Note that the CNAME alias masks your real IP address - a fundamental advantage of CF. Naming the A-record directly as your domain (example.com) would allow anyone to see your real IP address just by ping example.com. Try it!`

I click the orange cloud with A-record then real IP hidden.
Does I misunderstanding ?

**Comment by dcerisano** [comment]
The current method is more portable than relying on CF UX.
