### ISSUE TITLE
Unable to location Authorization ID

### ISSUE THREAD

**Issue by Trinitrogen** [dcerisano/cloudflare-dynamic-dns#7]
I'm unable cloudflare-dynamic-dns.sh script. I've added my Zone ID from my overview page, and global API key. I've updated the email. when I run the script I get the following output which didn't seem correct

{"result":[],"success":true,"errors":[],"messages":[],"result_info":{"page":1,"per_page":100,"count":0,"total_count":0,"total_pages":1}

I had to update the URL in curl to point toward type=A&name=dynamic._example.com_" to get a response with the record ID in it.

**Comment by dcerisano** [comment]
There is no `cloudflare-dynamic-dns.sh` script.
Could you please attach:

-  exact script name
-  exact OS version you tested on
-  exact change you made to the script
